### ISSUE TITLE
C notation

### ISSUE THREAD

**Issue by voghDev** [alexsimo/delightful-persistence#1]
Hi ma friend ^^

why do you use C notation for method signatures? on [have_created_all_columns](https://github.com/alexsimo/delightful-persistence/blob/master/app/src/androidTest/java/com/alexsimo/delightfulpersistence/database/BooksTableShould.java) for example

Don't mean to troll you at all, just curious about that :) 

Congrats for the repo, looks brilliant!

**Comment by alexsimo** [comment]
Hello @voghDev! 😃 
It makes tests name more readable for me. That's the only explanation. 

Thanks buddy!!

**Comment by voghDev** [comment]
ok great, thought it was because of a book recomendation, or another reason :)

keep up the good work!!
